export const colors = [
  { name: "red", value: "أحمر" },
  { name: "blue", value: "أزرق" },
  { name: "green", value: "أخضر" },
  { name: "yellow", value: "أصفر" },
  { name: "orange", value: "برتقالي" },
  { name: "purple", value: "أرجواني" },
  { name: "white", value: "أبيض" },
  { name: "black", value: "أسود" },
  { name: "gray", value: "رمادي" },
  { name: "silver", value: "فضي" },
  { name: "pink", value: "وردي" },
  { name: "brown", value: "بني" },
  { name: "beige", value: "بيج" },
  { name: "gold", value: "ذهبي" },
  { name: "bronze", value: "برونزي" },
  { name: "navy", value: "أزرق داكن" },
  { name: "teal", value: "تركوازي" },
  { name: "turquoise", value: "أزرق مائي" },
  { name: "magenta", value: "أرجواني زهري" },
  { name: "maroon", value: "كستنائي" },
  { name: "olive", value: "زيتوني" },
  { name: "lime", value: "ليموني" },
  { name: "ivory", value: "عاجي" },
];
